### ISSUE TITLE
SBOM Operator - Incorrect env var indentation

### ISSUE THREAD

**Issue by mspoeri** [ckotzbauer/helm-charts#111]
When providing additional environment variables via the `envVars` section, the indentation of the template is broken.

## Given

values.yaml
```yaml
envVars:
- name: TEST_VAR
  value: TEST
```
Command:
```bash
helm template ./charts/sbom-operator --dry-run --debug --generate-name -f values.yaml
```

## Result

```
Error: YAML parse error on sbom-operator/templates/deployment.yaml: error converting YAML to JSON: yaml: line 33: did not find expected key
```

template.yaml
```yaml
# Source: sbom-operator/templates/deployment.yaml
# Document has been shortened for clarity!

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sbom-operator

# Document shrinked for better understandability
spec:
    spec:
      containers:
        - name: sbom-operator
          image: "ghcr.io/ckotzbauer/sbom-operator:0.13.0"
          imagePullPolicy: IfNotPresent
          args:
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
# ---> Indentation of 10 expected but 12 is rendered          
            - name: TEST_VAR
              value: TEST
```
